postgres:
  restart: always
  image: postgres:9.4.5
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  expose:
    - "5432"
  ports:
    - 5432:5432

application:
  build: .
  command: npm start
  ports:
    - 8080:8080
  links:
    - postgres
  environment :
    - POSTGRES_PORT_5432_TCP_PORT=POSTGRES_PORT_5432_TCP_PORT
    - POSTGRES_PORT_5432_TCP_ADDR=POScdTGRES_PORT_5432_TCP_ADDR